### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by insoz** [robertstettner/drone-mvn-auth#1]
```bash
-- Preparing Maven for authentication...
/plugin/plugin.js:24
    return `<profile><id>${profile.id}</id><repositories>${profile.repositories.map(generateRepository('repository')).join('')}</repositories><pluginRepositories>${profile.plugin_repositories.map(generateRepository('pluginRepository')).join('')}</pluginRepositories></profile>`;

TypeError: Cannot read property 'map' of undefined
    at generateProfile (/plugin/plugin.js:24:192)
    at Array.map (native)
    at Object.init (/plugin/plugin.js:65:391)
    at Object.<anonymous> (/plugin/index.js:3:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

**Comment by robertstettner** [comment]
Could you please supply me with the input that created this error?

**Comment by insoz** [comment]
```bash
authenticate:
    image: robertstettner/drone-mvn-auth
    profiles:
      - id: aa
        repositories:
          - id: aa
            name: nexus
            url: http://ip:8081/nexus/content/groups/public/
            layout: default
    active_profiles:
      - aa
```

**Comment by robertstettner** [comment]
Issue has be resolved and build passed with new Docker image artifact pushed.
